### PR TITLE
Update source.txt

### PR DESCRIPTION
**Pull request by obeho**
Use Full list instead of Basic. https://oisd.nl/?p=faq#basic

### CODE REVIEW

**Comment by ookangzheng** [comment]
Most of the major blocklists are listed in BlahDNS `source.txt`, also included sources will combine other blocklists as well. 
In order to make DNS resolution more responsive, I think would be good to use OISD Basic instead of Full list.

**Comment by obeho** [comment]
> make DNS resolution more responsive

fair enough.

**Comment by obeho** [comment]
@ookangzheng Can [this ](https://github.com/AdguardTeam/cname-trackers) be integrated into BlahDNS blocklists?

A/c to them it is _the full list of all known CNAME-cloaked trackers_.

**Comment by ookangzheng** [comment]
I added this 2 CNAME blacklist

1. https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardCNAME.txt
2. https://adzhosts.eu/privacy/cname.txt 

Other third parties blocklist will include https://github.com/AdguardTeam/cname-trackers, I guess soon...

**Pull request closed without merging**
